---
version: "3.9"

services:
  smartgic_skill_sonos_controller:
    container_name: smartgic_skill_sonos_controller
    hostname: smartgic_skill_sonos_controller
    restart: unless-stopped
    image: smartgic/smartgic-skill-sonos-controller:${VERSION}
    pull_policy: always
    network_mode: host
    ipc: host
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
